<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>org.netbeans.modules.ruby</groupId>
        <artifactId>community-ruby</artifactId>
        <version>1.0-SNAPSHOT</version>
    </parent>

    <groupId>org.netbeans.modules.ruby</groupId>
    <artifactId>kit</artifactId>
    <version>1.0-SNAPSHOT</version>
    <packaging>nbm</packaging>

    <name>ruby.kit</name>
    
    <build>
        <finalName>ruby-${artifactId}-${version}</finalName>
        <plugins>
            <plugin>
                <groupId>org.apache.netbeans.utilities</groupId>
                <artifactId>nbm-maven-plugin</artifactId>
                <extensions>true</extensions>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-jar-plugin</artifactId>
                <configuration>
                    <archive>
                        <manifestFile>${project.build.outputDirectory}/META-INF/MANIFEST.MF</manifestFile>
                    </archive>
                </configuration>
            </plugin>
        </plugins>
    </build>
    <dependencies>
        <dependency>
            <groupId>org.netbeans.libs</groupId>
            <artifactId>jrubyparser</artifactId>
            <version>1.0-SNAPSHOT</version>
        </dependency>
        <dependency>
            <groupId>org.netbeans.modules.jellytools.ruby</groupId>
            <artifactId>jellytools.ruby</artifactId>
            <version>1.0-SNAPSHOT</version>
        </dependency>
<!--        <dependency>
            <groupId>org.netbeans.modules.ruby</groupId>
            <artifactId>org.jruby.distro</artifactId>
            <version>1.0-SNAPSHOT</version>
        </dependency>-->
        <dependency>
            <groupId>org.netbeans.modules.ruby</groupId>
            <artifactId>rakeproject</artifactId>
            <version>1.0-SNAPSHOT</version>
        </dependency>
        <dependency>
            <groupId>org.netbeans.modules.ruby</groupId>
            <artifactId>samples.depot</artifactId>
            <version>1.0-SNAPSHOT</version>
        </dependency>
        <dependency>
            <groupId>org.netbeans.modules.ruby</groupId>
            <artifactId>platform</artifactId>
            <version>1.0-SNAPSHOT</version>
        </dependency>
        <dependency>
            <groupId>org.netbeans.modules.ruby</groupId>
            <artifactId>editing</artifactId>
            <version>1.0-SNAPSHOT</version>
        </dependency>
        <dependency>
            <groupId>org.netbeans.modules.ruby.rhtml</groupId>
            <artifactId>ruby.rhtml</artifactId>
            <version>1.0-SNAPSHOT</version>
        </dependency>
        <dependency>
            <groupId>org.netbeans.modules.ruby</groupId>
            <artifactId>codecoverage</artifactId>
            <version>1.0-SNAPSHOT</version>
        </dependency>
        <dependency>
            <groupId>org.netbeans.modules.ruby</groupId>
            <artifactId>project</artifactId>
            <version>1.0-SNAPSHOT</version>
        </dependency>
        <dependency>
            <groupId>org.netbeans.modules.ruby</groupId>
            <artifactId>javaint</artifactId>
            <version>1.0-SNAPSHOT</version>
        </dependency>
        <dependency>
            <groupId>org.netbeans.modules.ruby</groupId>
            <artifactId>debugger</artifactId>
            <version>1.0-SNAPSHOT</version>
        </dependency>
        <dependency>
            <groupId>org.netbeans.modules.ruby</groupId>
            <artifactId>hints</artifactId>
            <version>1.0-SNAPSHOT</version>
        </dependency>
        <dependency>
            <groupId>org.netbeans.modules.ruby</groupId>
            <artifactId>extrahints</artifactId>
            <version>1.0-SNAPSHOT</version>
        </dependency>
        <dependency>
            <groupId>org.netbeans.modules.ruby</groupId>
            <artifactId>railsprojects</artifactId>
            <version>1.0-SNAPSHOT</version>
        </dependency>
        <dependency>
            <groupId>org.netbeans.modules.ruby</groupId>
            <artifactId>refactoring</artifactId>
            <version>1.0-SNAPSHOT</version>
        </dependency>
        <dependency>
            <groupId>org.netbeans.modules</groupId>
            <artifactId>spellchecker.bindings.ruby</artifactId>
            <version>1.0-SNAPSHOT</version>
        </dependency>
    </dependencies>
</project>
