<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>org.netbeans.modules.ruby</groupId>
        <artifactId>community-ruby</artifactId>
        <version>1.0-SNAPSHOT</version>
    </parent>

    <groupId>org.netbeans.modules.jellytools.ruby</groupId>
    <artifactId>jellytools.ruby</artifactId>
    <packaging>nbm</packaging>

    <name>jellytools.ruby</name>

    <properties>
        <xtest.jruby.home>${settings.localRepository}/org/jruby/jruby/1.7.27</xtest.jruby.home>
        <xtest.data>${project.build.directory}/test-classes/data</xtest.data>
        <all.clusters>${project.build.directory}/${brandingToken}</all.clusters>
        <cluster.path.final>${netbeans.installation}/harness;${netbeans.installation}/ide;${netbeans.installation}/nb;${netbeans.installation}/platform;${project.build.directory}/nbm/netbeans/${brandingToken}</cluster.path.final>
    </properties>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.netbeans.utilities</groupId>
                <artifactId>nbm-maven-plugin</artifactId>
                <extensions>true</extensions>
                <configuration>
                    <publicPackages>
                        <publicPackage>org.netbeans.jellytools</publicPackage>
                        <publicPackage>org.netbeans.jellytools.actions</publicPackage>
                    </publicPackages>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-jar-plugin</artifactId>
                <version>3.1.2</version>
                <configuration>
                    <archive>
                        <manifestFile>${project.build.outputDirectory}/META-INF/MANIFEST.MF</manifestFile>
                    </archive>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <version>3.0.0-M5</version>
                <configuration>
                    <systemPropertyVariables>
                        <xtest.jruby.home>${xtest.jruby.home}/</xtest.jruby.home>
                        <xtest.data>${xtest.data}</xtest.data>
                        <cluster.path.final>${cluster.path.final}</cluster.path.final>
                    </systemPropertyVariables>
                </configuration>
            </plugin>
        </plugins>
    </build>

    <dependencies>
        <dependency>
            <groupId>org.netbeans.cluster</groupId>
            <artifactId>platform</artifactId>
            <version>${netbeans.version}</version>
            <type>pom</type>
        </dependency>
        <dependency>
            <groupId>org.netbeans.api</groupId>
            <artifactId>org-netbeans-modules-jellytools-ide</artifactId>
            <version>${netbeans.version}</version>
        </dependency>
        <dependency>
            <groupId>org.netbeans.api</groupId>
            <artifactId>org-netbeans-modules-jellytools-platform</artifactId>
            <version>${netbeans.version}</version>
        </dependency>
        <dependency>
            <groupId>org.netbeans.api</groupId>
            <artifactId>org-netbeans-modules-jemmy</artifactId>
            <version>${netbeans.version}</version>
        </dependency>


        <dependency>
            <groupId>org.netbeans.api</groupId>
            <artifactId>org-netbeans-libs-junit4</artifactId>
            <version>${netbeans.version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.netbeans.modules.ruby</groupId>
            <artifactId>project</artifactId>
            <version>1.0-SNAPSHOT</version>
            <scope>test</scope>
        </dependency>
    </dependencies>
</project>
